#!/bin/sh

set -e

export \
    CLAIR_OUTPUT=${PLUGIN_CLAIR_OUTPUT:-Unknown} \
    CLAIR_THRESHOLD=${PLUGIN_CLAIR_THRESHOLD:-0} \
    DOCKER_INSECURE=${PLUGIN_DOCKER_INSECURE:-false} \
    REGISTRY_INSECURE=${PLUGIN_REGISTRY_INSECURE:-false} \
    JSON_OUTPUT=${PLUGIN_JSON_OUTPUT:-false} \
    CLAIR_ADDR=${PLUGIN_CLAIR_ADDR} \
    DOCKER_USER=${PLUGIN_DOCKER_USER} \
    DOCKER_PASSWORD=${PLUGIN_DOCKER_PASSWORD}

exec /usr/bin/klar "${PLUGIN_REPO}"
